"""cascade delete for masterclass

Revision ID: 0a1bb8803498
Revises: 64c11f0dda06
Create Date: 2026-06-12 16:54:05.008032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1bb8803498'
down_revision = '64c11f0dda06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('masterclass_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('tests_masterclass_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'masterclasses', ['masterclass_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tests_masterclass_id_fkey'), 'masterclasses', ['masterclass_id'], ['id'])
        batch_op.alter_column('masterclass_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
