"""cascade delete for webinar_views

Revision ID: 64c11f0dda06
Revises: edeb4a8f3425
Create Date: 2026-06-12 16:30:13.411220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c11f0dda06'
down_revision = 'edeb4a8f3425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar_views', schema=None) as batch_op:
        batch_op.alter_column('webinar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('webinar_views_webinar_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'webinars', ['webinar_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('webinar_views_webinar_id_fkey'), 'webinars', ['webinar_id'], ['id'])
        batch_op.alter_column('webinar_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
