"""initial schema

Revision ID: b8f2b79612ff
Revises: 
Create Date: 2026-05-13 18:38:40.847413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8f2b79612ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
        batch_op.drop_constraint(batch_op.f('appeals_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('certificates_masterclass_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('certificates_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'masterclasses', ['masterclass_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('masterclass_progress', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('masterclass_progress_user_id_masterclass_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('masterclass_progress_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('masterclass_progress_masterclass_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_progress_certificate'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'masterclasses', ['masterclass_id'], ['id'])
        batch_op.create_foreign_key(None, 'certificates', ['certificate_id'], ['id'])

    with op.batch_alter_table('masterclasses', schema=None) as batch_op:
        batch_op.alter_column('passing_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('80'))

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('survey_questions_survey_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'surveys', ['survey_id'], ['id'])

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.alter_column('answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('survey_responses_user_id_survey_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('survey_responses_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('survey_responses_survey_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'surveys', ['survey_id'], ['id'])

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('tests_masterclass_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'masterclasses', ['masterclass_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('webinar_views', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('webinar_views_user_id_webinar_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('webinar_views_webinar_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('webinar_views_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'webinars', ['webinar_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinar_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('webinar_views_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('webinar_views_webinar_id_fkey'), 'webinars', ['webinar_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('webinar_views_user_id_webinar_id_key'), ['user_id', 'webinar_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tests_masterclass_id_fkey'), 'masterclasses', ['masterclass_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('survey_responses_survey_id_fkey'), 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('survey_responses_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('survey_responses_user_id_survey_id_key'), ['user_id', 'survey_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('survey_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('survey_questions_survey_id_fkey'), 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('masterclasses', schema=None) as batch_op:
        batch_op.alter_column('passing_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('80'))

    with op.batch_alter_table('masterclass_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_progress_certificate'), 'certificates', ['certificate_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('masterclass_progress_masterclass_id_fkey'), 'masterclasses', ['masterclass_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('masterclass_progress_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('masterclass_progress_user_id_masterclass_id_key'), ['user_id', 'masterclass_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('certificates_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('certificates_masterclass_id_fkey'), 'masterclasses', ['masterclass_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appeals_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))

    # ### end Alembic commands ###
